"""output/stage6 — the reusable Stage-6 final-evaluation architecture for Crucible.

Stage 6 asks the ONLY question that proves the Teacher RFT worked:

    Does the TRAINED Teacher generate environments that cause FRESH PPO Players to
    improve MORE on HELD-OUT tasks than environments generated by the BASE Teacher?

This package is the decomposition of the old monolithic
``output/eval_base_vs_trained.py`` into reusable pieces, so the same pipeline runs
for any game, any base/trained Teacher handle (Fireworks id OR local LoRA adapter
path), and a report can be regenerated from saved JSON without rerunning PPO.

Modules
-------
* ``handles``      — resolve a Teacher handle string -> a Teacher (Fireworks OR local).
* ``games``        — the game registry/router (fighter / target_knockback / koth).
* ``config``       — the frozen fairness invariant (one config used for BOTH models).
* ``aggregate``    — mean / std / confidence-interval / diversity math (no scipy).
* ``anti_gaming``  — the gaming checks that can FAIL a run even when reward rose.
* ``report``       — charts + Markdown report + replay manifest from a result JSON.
* ``evaluator``    — the orchestrator that ties it all together (the decider).
"""
